title: Your awesome title
email: your-email@example.com
baseurl: "/tomas_m.gitthub.io"
url: "https://tywyllsoftware.github.io"
twitter_username: jekyllrb
github_username: jekyll

theme: minima
plugins:
  - jekyll-feed